jobs:
  build:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Initialize
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Check
        run: ./workflow/main

name: Verify

on:
  schedule:
    - cron: "30 */6 * * *"
